[package]
name = "command_line_text_editor"
version = "0.1.0"
authors = ["Nilesh Suthar <nilesh.suthar@acuteinformatics.in"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
